// <auto-generated />
using System;
using FileReception.Infrastructure.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FileReception.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FileReception.Domain.Entities.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Company", (string)null);
                });

            modelBuilder.Entity("FileReception.Domain.Entities.File", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ExpectedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("FileLayoutId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("FileLayoutId");

                    b.HasIndex("StatusId");

                    b.ToTable("File", (string)null);
                });

            modelBuilder.Entity("FileReception.Domain.Entities.FileLayout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("FileLayout", (string)null);
                });

            modelBuilder.Entity("FileReception.Domain.Entities.FileLayoutField", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("End")
                        .HasColumnType("int");

                    b.Property<int>("FileLayoutFieldTypeId")
                        .HasColumnType("int");

                    b.Property<int>("FileLayoutId")
                        .HasColumnType("int");

                    b.Property<int>("Start")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FileLayoutFieldTypeId");

                    b.HasIndex("FileLayoutId");

                    b.ToTable("FileLayoutField", (string)null);
                });

            modelBuilder.Entity("FileReception.Domain.Entities.FileLayoutFieldType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("FileLayoutFieldType", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "ALFA"
                        },
                        new
                        {
                            Id = 2,
                            Name = "NUM"
                        });
                });

            modelBuilder.Entity("FileReception.Domain.Entities.FileProcess", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("FileId")
                        .HasColumnType("int");

                    b.Property<string>("FilePathBackup")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsValid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("FileId");

                    b.ToTable("FileProcess", (string)null);
                });

            modelBuilder.Entity("FileReception.Domain.Entities.FileStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("FileStatus", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Não Recepcionado"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Recepcionado"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Erro"
                        });
                });

            modelBuilder.Entity("FileReception.Domain.Entities.File", b =>
                {
                    b.HasOne("FileReception.Domain.Entities.FileLayout", "FileLayout")
                        .WithMany("Files")
                        .HasForeignKey("FileLayoutId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FileReception.Domain.Entities.FileStatus", "FileStatus")
                        .WithMany("Files")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FileLayout");

                    b.Navigation("FileStatus");
                });

            modelBuilder.Entity("FileReception.Domain.Entities.FileLayout", b =>
                {
                    b.HasOne("FileReception.Domain.Entities.Company", "Company")
                        .WithMany("FileLayouts")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("FileReception.Domain.Entities.FileLayoutField", b =>
                {
                    b.HasOne("FileReception.Domain.Entities.FileLayoutFieldType", "FileLayoutFieldType")
                        .WithMany("Fields")
                        .HasForeignKey("FileLayoutFieldTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FileReception.Domain.Entities.FileLayout", "FileLayout")
                        .WithMany("Fields")
                        .HasForeignKey("FileLayoutId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FileLayout");

                    b.Navigation("FileLayoutFieldType");
                });

            modelBuilder.Entity("FileReception.Domain.Entities.FileProcess", b =>
                {
                    b.HasOne("FileReception.Domain.Entities.File", "File")
                        .WithMany("Processes")
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("File");
                });

            modelBuilder.Entity("FileReception.Domain.Entities.Company", b =>
                {
                    b.Navigation("FileLayouts");
                });

            modelBuilder.Entity("FileReception.Domain.Entities.File", b =>
                {
                    b.Navigation("Processes");
                });

            modelBuilder.Entity("FileReception.Domain.Entities.FileLayout", b =>
                {
                    b.Navigation("Fields");

                    b.Navigation("Files");
                });

            modelBuilder.Entity("FileReception.Domain.Entities.FileLayoutFieldType", b =>
                {
                    b.Navigation("Fields");
                });

            modelBuilder.Entity("FileReception.Domain.Entities.FileStatus", b =>
                {
                    b.Navigation("Files");
                });
#pragma warning restore 612, 618
        }
    }
}
